### PR TITLE
Add info about boost support

### PR DESCRIPTION
**Pull request by mmatrosov**
Add column "boost version" to the table. Add corresponding badges to compilers. Remove boost badge from Compiler Explorer (Godbolt), it does not support boost (or do I miss something?).

### CODE REVIEW

**Comment by adishavit** [comment]
CE does have an (underdocumented) option to include boost.
See [here](https://github.com/mattgodbolt/compiler-explorer/issues/154).
https://godbolt.org/g/e1Pm0H

**Comment by mmatrosov** [comment]
Indeed, reverted it and added version to the table.

**Comment by adishavit** [comment]
If it's getting its own column, I think it's best to also add a dedicated (pink) badge independent of the (other) libraries badge: 

What do you think?
I defer to @arnemertz

**Comment by mmatrosov** [comment]
Ok, @arnemertz , should I add a new badge?

**Comment by adishavit** [comment]
@arnemertz : what do you say, if it gets a column in the table, then its common enough and important enough to get a separate badge, no?

**Comment by arnemertz** [comment]
Thanks for the work! I like the idea of the special Boost badge, after all, it's like a second standard library.
With that regard, what do you think about giving it a blue badge like the C++ version, right after that one?

**Comment by arnemertz** [comment]
Update: after consulting with @adishavit I agree with him that we should leave it as a pink badge.

**Comment by arnemertz** [comment]
Added/modified badges for Boost and other libraries 
https://github.com/arnemertz/online-compilers/commit/8723494c9fa424b19114d50fc3a62418922e1b6d

**Pull request merged**
